# Generated by Django 4.0.6 on 2022-07-23 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='extension',
        ),
        migrations.AddField(
            model_name='banner',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='uploadedFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='banner/'),
            preserve_default=False,
        ),
    ]
