# Generated by Django 4.0.6 on 2022-08-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tax', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_neto',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_sale',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
