# Generated by Django 4.0.6 on 2022-08-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_tax_rename_total_neto_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
