# Generated by Django 4.0.6 on 2022-07-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='banner',
            field=models.FileField(upload_to='subcategories/'),
        ),
    ]
