# Generated by Django 4.0.6 on 2022-08-17 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='parcel/')),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.parcel'),
        ),
    ]
