# Generated by Django 4.0.6 on 2022-08-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_alter_subcategory_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('SubCategory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adm.subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.category')),
            ],
        ),
    ]
