# Generated by Django 4.0.6 on 2022-08-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_parcel_order_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.parcel'),
        ),
    ]
