# Generated by Django 4.0.6 on 2022-08-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='subcategory',
        ),
    ]
