# Generated by Django 4.0.6 on 2022-08-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_userdetail_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Business', max_length=50)),
                ('address', models.CharField(default='My Address', max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(default='contacto@mybusiness.com', max_length=254)),
            ],
        ),
    ]
