# Generated by Django 4.0.6 on 2022-08-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_rename_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='category',
        ),
    ]
