# Generated by Django 4.0.6 on 2022-08-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.FileField(default=1, upload_to='settings/'),
            preserve_default=False,
        ),
    ]
