# Generated by Django 4.0.6 on 2022-08-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_rename_subcategory_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='products/'),
        ),
    ]
