# Generated by Django 4.0.6 on 2022-08-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='products/'),
        ),
    ]
