# Generated by Django 4.0.6 on 2022-09-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_userdetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('uploadedFile', models.FileField(upload_to='banner/')),
                ('status', models.BooleanField(default=True)),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=51),
        ),
    ]
