# Generated by Django 4.0.6 on 2022-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_secondarybanner_alter_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
