# Generated by Django 4.0.6 on 2022-09-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='facebook',
            field=models.CharField(default='My_Address', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.CharField(default='My_Address', max_length=255),
        ),
    ]
