# Generated by Django 4.0.6 on 2022-08-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
