# Generated by Django 4.0.6 on 2022-10-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_settings_facebook_settings_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.parcel'),
        ),
    ]
