# Generated by Django 3.2.15 on 2022-09-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_alter_userdetail_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
