# Generated by Django 3.2.15 on 2022-09-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_auto_20220924_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='parcel/'),
        ),
    ]
