# Generated by Django 4.0.6 on 2022-08-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_cart_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
